name: dbt_dqm
version: 0.1.0
config-version: 2
require-dbt-version: [">=1.11.0", "<1.12.0"]

model-paths: ["models"]
macro-paths: ["macros"]
clean-targets: ["target", "dbt_packages", "logs"]

on-run-end:
  - "{{ dbt_dqm.capture_test_results(results) }}"

models:
  dbt_dqm:
    +schema: "{{ var('dbt_dqm_schema', none) }}"
    dqm_reconcile:
      +pre-hook:
        - "{{ dbt_dqm.capture_tables_ddl() }}"
        - "{{ dbt_dqm.migrate_occurrence_schema() }}"
